In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import yaml
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [6]:
df_gb = pd.read_csv(config["input_data"]["file4"])
df_gb.head()

,Realm_Name,Ecoregion_Name,Country_Name,Distance_to_Shore,Exposure,Cyclone_Frequency,Date_Day,Date_Month,Date_Year,Depth_m,...,SSTA_Standard_Deviation,SSTA_Mean,SSTA_DHW,SSTA_DHW_Standard_Deviation,TSA,TSA_Standard_Deviation,Date,Site_Comments,Sample_Comments,Bleaching_Comments
0,Central Indo-Pacific,Central and northern Great Barrier Reef,Australia,57467.04,Sheltered,48.94,9,7,2017,5,...,0.79,0,0.0,2.89,-4.71,2.06,2017-07-09,nd,nd,nd
1,Central Indo-Pacific,Central and northern Great Barrier Reef,Australia,57467.04,Sheltered,48.94,9,7,2017,5,...,0.79,0,0.0,2.89,-4.71,2.06,2017-07-09,nd,nd,nd
2,Central Indo-Pacific,Central and northern Great Barrier Reef,Australia,57656.01,Sheltered,48.94,9,7,2017,2,...,0.79,0,0.0,2.89,-4.71,2.06,2017-07-09,nd,nd,nd
3,Central Indo-Pacific,Central and northern Great Barrier Reef,Australia,57656.01,Sheltered,48.94,9,7,2017,2,...,0.79,0,0.0,2.89,-4.71,2.06,2017-07-09,nd,nd,nd
4,Central Indo-Pacific,Central and northern Great Barrier Reef,Australia,43199.05,Sheltered,43.31,7,7,2017,4,...,0.82,0,0.0,3.07,-4.77,2.20,2017-07-07,nd,nd,nd

In [12]:
print(list(df_gb.columns))

['Realm_Name', 'Ecoregion_Name', 'Country_Name', 'Distance_to_Shore', 'Exposure', 'Cyclone_Frequency', 'Date_Day', 'Date_Month', 'Date_Year', 'Depth_m', 'Substrate_Name', 'Percent_Cover', 'Bleaching_Level', 'Percent_Bleaching', 'ClimSST', 'SSTA', 'SSTA_Standard_Deviation', 'SSTA_Mean', 'SSTA_DHW', 'SSTA_DHW_Standard_Deviation', 'TSA', 'TSA_Standard_Deviation', 'Date', 'Site_Comments', 'Sample_Comments', 'Bleaching_Comments']

In [32]:
#see all values of columns
pd.set_option('display.max_rows', None)
# Reset option to default if needed
#pd.reset_option('display.max_rows')

In [51]:
def clean_gb(df_gb):
    #Convert all column names to lowercase
    df_gb.columns = df_gb.columns.str.lower()

   # Specify columns to drop
    columns_to_drop = [
        'realm_name', 'date_day', 'date_month', 'date_year', 
        'depth_m', 'sample_comments', 'site_comments',  
        'substrate_name', 'percent_cover', 'ssta_mean', 
        'ssta_dhw', 'ssta_dhw_standard_deviation', 
        'tsa', 'tsa_standard_deviation', 'bleaching_comments'
    ]

    # Drop specified columns
    df_gb = df_gb.drop(columns=columns_to_drop, errors='ignore')

    # Remove duplicate rows
    df_gb = df_gb.drop_duplicates()

    # Backfill NaN values in 'percent_bleaching'
    df_gb['percent_bleaching'] = df_gb['percent_bleaching'].ffill()

    # Return the cleaned DataFrame
    return df_gb

# Clean the DataFrame
df_gb_cleaned = clean_gb(df_gb)

# Display the cleaned DataFrame
display(df_gb_cleaned)

,ecoregion_name,country_name,distance_to_shore,exposure,cyclone_frequency,bleaching_level,percent_bleaching,climsst,ssta,ssta_standard_deviation,date
0,Central and northern Great Barrier Reef,Australia,57467.04,Sheltered,48.94,Population,0.00,296.66,0.42,0.79,2017-07-09
2,Central and northern Great Barrier Reef,Australia,57656.01,Sheltered,48.94,Population,0.00,296.66,0.42,0.79,2017-07-09
4,Central and northern Great Barrier Reef,Australia,43199.05,Sheltered,43.31,Population,0.00,296.51,0.77,0.82,2017-07-07
6,Central and northern Great Barrier Reef,Australia,41586.65,Sheltered,48.37,Population,0.00,298.59,-2.30,2.23,2017-08-05
8,Central and northern Great Barrier Reef,Australia,145.07,Exposed,43.52,Population,0.00,295.84,1.62,1.02,2017-07-07
10,Southern Great Barrier Reef,Australia,54.69,Sheltered,51.46,Population,0.25,299.83,0.00,0.72,2015-11-24
12,Southern Great Barrier Reef,Australia,459.75,Sheltered,51.46,Population,0.25,297.41,0.80,0.72,2016-09-22
14,Southern Great Barrier Reef,Australia,184.65,Sheltered,51.57,Population,0.25,297.41,0.80,0.72,2016-09-22
16,Central and northern Great Barrier Reef,Australia,57425.12,Sheltered,48.94,Population,0.50,296.66,0.42,0.79,2017-07-08
18,Central and northern Great Barrier Reef,Australia,220.26,Exposed,43.52,Population,0.50,301.47,1.59,1.02,2017-10-15
20,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,0.75,301.69,-0.14,0.98,2015-10-24
22,Southern Great Barrier Reef,Australia,459.75,Sheltered,51.46,Population,0.75,299.99,0.39,0.72,2015-11-27
24,Southern Great Barrier Reef,Australia,782.39,Sheltered,51.57,Population,0.75,297.41,0.80,0.72,2016-09-22
26,Southern Great Barrier Reef,Australia,2173.19,Sheltered,51.57,Population,1.00,299.92,0.42,0.73,2015-11-24
28,Southern Great Barrier Reef,Australia,1345.62,Sheltered,51.57,Population,1.00,299.92,0.42,0.73,2015-11-24
30,Southern Great Barrier Reef,Australia,782.39,Sheltered,51.57,Population,1.00,299.99,0.39,0.72,2015-11-28
32,Southern Great Barrier Reef,Australia,95.43,Sheltered,51.57,Population,1.00,299.99,0.39,0.72,2015-11-28
34,Southern Great Barrier Reef,Australia,106.65,Sheltered,51.57,Population,1.00,299.99,0.39,0.72,2015-11-29
36,Southern Great Barrier Reef,Australia,94.80,Sheltered,51.46,Population,1.00,299.99,0.39,0.72,2015-11-25
38,Southern Great Barrier Reef,Australia,1739.41,Exposed,51.57,Population,1.00,299.99,0.39,0.72,2015-11-25
40,Southern Great Barrier Reef,Australia,847.35,Exposed,51.57,Population,1.00,299.99,0.39,0.72,2015-11-28
42,Southern Great Barrier Reef,Australia,1152.07,Exposed,51.57,Population,1.00,299.99,0.39,0.72,2015-11-25
44,Southern Great Barrier Reef,Australia,847.35,Exposed,51.57,Population,1.00,297.05,0.38,0.72,2016-09-20
46,Central and northern Great Barrier Reef,Australia,19.02,Sheltered,45.33,Population,1.00,296.48,1.76,0.93,2017-08-06
48,Central and northern Great Barrier Reef,Australia,2795.93,Sheltered,43.52,Population,1.00,298.70,1.94,1.02,2017-03-18
50,Central and northern Great Barrier Reef,Australia,2865.08,Sheltered,43.52,Population,1.00,298.70,1.94,1.02,2017-03-18
52,Southern Great Barrier Reef,Australia,2173.19,Sheltered,51.57,Population,1.00,299.15,0.94,0.73,2017-10-29
54,Southern Great Barrier Reef,Australia,665.19,Sheltered,51.46,Population,1.00,299.35,0.82,0.72,2017-11-03
56,Southern Great Barrier Reef,Australia,682.44,Exposed,51.46,Population,1.00,299.08,0.82,0.72,2017-10-31
58,Southern Great Barrier Reef,Australia,847.35,Exposed,51.57,Population,1.00,299.08,0.82,0.72,2017-10-31
60,Central and northern Great Barrier Reef,Australia,29487.39,Sheltered,48.10,Population,1.25,296.83,0.98,0.77,2017-08-07
62,Central and northern Great Barrier Reef,Australia,40871.05,Sheltered,48.37,Population,1.25,298.59,-2.30,2.23,2017-08-05
64,Southern Great Barrier Reef,Australia,459.75,Sheltered,51.46,Population,1.25,299.35,0.82,0.72,2017-11-02
66,Central and northern Great Barrier Reef,Australia,53198.14,Exposed,50.40,Population,1.50,301.47,-0.20,0.87,2016-10-30
68,Southern Great Barrier Reef,Australia,1345.62,Sheltered,51.57,Population,1.75,299.15,0.94,0.73,2017-10-29
70,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,2.00,297.64,0.30,0.88,2015-08-02
72,Southern Great Barrier Reef,Australia,1739.41,Exposed,51.57,Population,2.00,297.05,0.38,0.72,2016-09-19
74,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,2.00,294.89,-0.78,0.98,2017-06-09
76,Southern Great Barrier Reef,Australia,930.80,Exposed,51.57,Population,2.00,299.35,0.82,0.72,2017-11-03
78,Central and northern Great Barrier Reef,Australia,224.53,Exposed,43.52,Population,2.25,301.69,-0.09,1.02,2015-10-24
80,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,2.25,294.89,-0.78,0.98,2017-06-09
82,Central and northern Great Barrier Reef,Australia,57761.46,Sheltered,48.94,Population,2.25,296.66,0.42,0.79,2017-07-08
84,Southern Great Barrier Reef,Australia,54.69,Sheltered,51.46,Population,2.75,297.05,0.38,0.72,2016-09-18
86,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,3.00,297.64,0.30,0.88,2015-08-02
88,Central and northern Great Barrier Reef,Australia,39847.16,Sheltered,71.88,Population,3.25,299.42,0.22,0.84,2015-09-13
90,Central and northern Great Barrier Reef,Australia,37626.29,Sheltered,52.46,Population,3.25,298.90,0.95,0.87,2015-08-30
92,Central and northern Great Barrier Reef,Australia,224.53,Exposed,43.52,Population,3.50,294.83,0.29,1.02,2017-06-09
94,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,3.50,301.53,1.36,0.85,2017-10-28
96,Southern Great Barrier Reef,Australia,1152.07,Exposed,51.57,Population,3.50,299.08,0.82,0.72,2017-10-30
98,Central and northern Great Barrier Reef,Australia,33605.64,Sheltered,71.88,Population,4.00,301.42,0.24,0.86,2016-10-29
100,Southern Great Barrier Reef,Australia,1152.07,Exposed,51.57,Population,4.00,297.05,0.38,0.72,2016-09-19
102,Southern Great Barrier Reef,Australia,192.41,Sheltered,51.46,Population,4.25,299.99,0.39,0.72,2015-11-27
104,Southern Great Barrier Reef,Australia,1345.62,Sheltered,51.57,Population,4.25,297.07,0.53,0.73,2016-09-18
106,Southern Great Barrier Reef,Australia,1739.41,Exposed,51.57,Population,4.25,299.08,0.82,0.72,2017-10-30
108,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,4.50,298.91,-2.03,2.48,2015-10-01
110,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,4.50,297.14,0.39,0.98,2016-04-09
112,Central and northern Great Barrier Reef,Australia,29934.17,Sheltered,48.10,Population,4.75,295.74,1.73,0.77,2016-05-28
114,Central and northern Great Barrier Reef,Australia,224.53,Exposed,43.52,Population,4.75,297.02,0.34,1.02,2016-04-10
116,Central and northern Great Barrier Reef,Australia,126.24,Sometimes,43.39,Population,5.00,295.18,1.64,0.98,2016-06-26
118,Southern Great Barrier Reef,Australia,95.43,Sheltered,51.57,Population,5.00,297.05,0.38,0.72,2016-09-19
120,Southern Great Barrier Reef,Australia,192.41,Sheltered,51.46,Population,5.00,297.41,0.80,0.72,2016-09-21
122,Southern Great Barrier Reef,Australia,106.65,Sheltered,51.57,Population,5.00,297.41,0.80,0.72,2016-09-21
124,Southern Great Barrier Reef,Australia,665.19,Sheltered,51.46,Population,5.25,297.05,0.38,0.72,2016-09-20
126,Southern Great Barrier Reef,Australia,226.58,Sheltered,51.46,Population,5.75,299.99,0.39,0.72,2015-11-26
128,Central and northern Great Barrier Reef,Australia,350.30,Sheltered,43.39,Population,6.00,298.66,2.78,0.98,2017-03-19
130,Southern Great Barrier Reef,Australia,26.88,Sheltered,43.06,Population,6.25,297.78,1.32,0.87,2016-03-26
132,Central and northern Great Barrier Reef,Australia,216.38,Sometimes,43.39,Population,6.25,298.66,2.78,0.98,2017-03-19
134,Central and northern Great Barrier Reef,Australia,2865.08,Sheltered,43.52,Population,6.50,296.78,1.64,1.02,2015-07-25
136,Southern Great Barrier Reef,Australia,2173.19,Sheltered,51.57,Population,6.50,297.07,0.53,0.73,2016-09-18
138,Southern Great Barrier Reef,Australia,54.69,Sheltered,51.46,Population,6.50,299.08,0.82,0.72,2017-10-29
140,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,8.25,297.14,0.39,0.98,2016-04-09
142,Central and northern Great Barrier Reef,Australia,2795.93,Sheltered,43.52,Population,8.75,296.78,1.64,1.02,2015-07-25
144,Central and northern Great Barrier Reef,Australia,46945.93,Sheltered,60.01,Population,8.75,299.46,0.19,0.85,2015-09-13
146,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,8.75,301.53,0.08,0.85,2016-10-30
148,Southern Great Barrier Reef,Australia,840.60,Sometimes,43.06,Population,8.75,297.78,1.32,0.87,2016-03-26
150,Central and northern Great Barrier Reef,Australia,49.79,Sheltered,46.88,Population,9.25,298.77,0.56,2.42,2016-04-23
152,Central and northern Great Barrier Reef,Australia,29008.14,Sheltered,48.10,Population,9.50,295.74,1.73,0.77,2016-05-28
154,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,10.00,301.53,0.08,0.85,2016-10-30
156,Southern Great Barrier Reef,Australia,226.58,Sheltered,51.46,Population,10.00,297.05,0.38,0.72,2016-09-20
158,Southern Great Barrier Reef,Australia,782.39,Sheltered,51.57,Population,10.00,299.35,0.82,0.72,2017-11-02
160,Southern Great Barrier Reef,Australia,184.65,Sheltered,51.57,Population,10.00,299.35,0.82,0.72,2017-11-04
162,Southern Great Barrier Reef,Australia,247.29,Exposed,39.06,Population,11.25,298.17,0.87,0.82,2016-03-27
164,Central and northern Great Barrier Reef,Australia,29008.14,Sheltered,48.10,Population,11.75,296.83,0.98,0.77,2017-08-07
166,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,12.50,299.85,-0.72,0.88,2015-10-02
168,Southern Great Barrier Reef,Australia,226.58,Sheltered,51.46,Population,12.50,299.35,0.82,0.72,2017-11-01
170,Central and northern Great Barrier Reef,Australia,216.38,Sometimes,43.39,Population,13.25,296.52,1.11,0.98,2015-07-26
172,Central and northern Great Barrier Reef,Australia,38514.12,Sheltered,48.80,Population,13.75,298.86,1.43,0.84,2015-08-29
174,Southern Great Barrier Reef,Australia,192.41,Sheltered,51.46,Population,15.00,299.08,0.82,0.72,2017-10-30
176,Southern Great Barrier Reef,Australia,94.80,Sheltered,51.46,Population,15.25,297.05,0.38,0.72,2016-09-20
178,Central and northern Great Barrier Reef,Australia,20.86,Sheltered,44.24,Population,16.25,301.74,0.97,0.87,2017-10-29
180,Central and northern Great Barrier Reef,Australia,40871.05,Sheltered,48.37,Population,17.25,298.51,0.06,2.23,2016-05-29
182,Central and northern Great Barrier Reef,Australia,19577.87,Exposed,43.97,Population,17.50,299.09,0.70,2.58,2016-10-12
184,Southern Great Barrier Reef,Australia,94.80,Sheltered,51.46,Population,17.50,299.35,0.82,0.72,2017-11-02
186,Central and northern Great Barrier Reef,Australia,350.30,Sheltered,43.39,Population,20.00,295.18,1.64,0.98,2016-06-26
188,Central and northern Great Barrier Reef,Australia,38506.76,Sheltered,48.80,Population,22.50,298.86,1.43,0.84,2015-08-29
190,Central and northern Great Barrier Reef,Australia,326.99,Sheltered,43.39,Population,24.25,296.53,1.11,0.96,2015-07-26
192,Southern Great Barrier Reef,Australia,211.24,Sheltered,39.06,Population,25.00,298.21,1.07,0.81,2016-03-27
194,Southern Great Barrier Reef,Australia,106.65,Sheltered,51.57,Population,25.00,299.35,0.82,0.72,2017-11-01
196,Central and northern Great Barrier Reef,Australia,35199.40,Sheltered,50.97,Population,28.75,298.87,0.83,0.88,2015-08-30
198,Southern Great Barrier Reef,Australia,95.43,Sheltered,51.57,Population,30.00,299.08,0.82,0.72,2017-10-31
200,Central and northern Great Barrier Reef,Australia,35199.40,Sheltered,50.97,Population,31.00,297.67,-0.43,0.88,2017-04-30
202,Central and northern Great Barrier Reef,Australia,41586.65,Sheltered,48.37,Population,32.50,298.51,0.06,2.23,2016-05-29
204,Central and northern Great Barrier Reef,Australia,22.86,Sheltered,45.33,Population,33.75,296.48,1.76,0.93,2017-08-06
206,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,35.00,299.85,-0.72,0.88,2015-10-02
208,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,35.00,296.86,-0.12,0.88,2017-05-01
210,Central and northern Great Barrier Reef,Australia,36098.44,Sheltered,50.97,Population,35.25,297.67,-0.43,0.88,2017-04-30
212,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,40.00,296.79,0.43,0.88,2016-04-23
214,Central and northern Great Barrier Reef,Australia,34986.69,Sheltered,50.97,Population,42.75,297.67,-0.43,0.88,2017-04-30
216,Central and northern Great Barrier Reef,Australia,31869.41,Sometimes,52.46,Population,52.50,297.55,1.60,0.87,2016-04-30
218,Central and northern Great Barrier Reef,Australia,35199.40,Sheltered,50.97,Population,56.25,297.67,0.82,0.88,2016-04-30
220,Central and northern Great Barrier Reef,Australia,2795.93,Sheltered,43.52,Population,57.50,295.29,1.71,1.02,2016-06-25
222,Central and northern Great Barrier Reef,Australia,39227.48,Sheltered,71.88,Population,58.75,298.16,0.79,0.84,2016-04-17
224,Central and northern Great Barrier Reef,Australia,46945.93,Sheltered,60.01,Population,60.00,298.34,0.92,0.85,2016-04-17
226,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,65.00,296.86,-0.12,0.88,2017-05-01
228,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,67.50,299.47,0.22,0.85,2015-09-12
230,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,72.50,298.15,0.64,0.85,2016-04-17
232,Central and northern Great Barrier Reef,Australia,39847.16,Sheltered,71.88,Population,75.75,298.73,0.85,0.84,2017-04-02
234,Central and northern Great Barrier Reef,Australia,46945.93,Sheltered,60.01,Population,77.50,298.90,1.25,0.85,2017-04-02
236,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,91.00,298.73,1.44,0.85,2017-04-01
238,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,95.50,298.73,1.44,0.85,2017-04-01
240,Central and northern Great Barrier Reef,Australia,22.86,Sheltered,45.33,nd,95.50,296.21,0.25,0.93,2016-04-25
242,Central and northern Great Barrier Reef,Australia,46.06,Sheltered,45.33,nd,95.50,296.21,0.25,0.93,2016-04-25
244,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,nd,95.50,296.79,0.43,0.88,2016-04-24
246,Southern Great Barrier Reef,Australia,665.19,Sheltered,51.46,nd,95.50,299.99,0.39,0.72,2015-11-27

In [49]:
df_gb_cleaned.to_csv('global_bleaching_cleaned.csv', index=False)

In [52]:
def sort_by_date(df, date_column):
    # Ensure the date column is in datetime format
    df[date_column] = pd.to_datetime(df[date_column])

    # Sort the DataFrame by the date column
    df_sorted = df.sort_values(by=date_column)

    # Reset the index to reflect the new ordering
    df_sorted.reset_index(drop=True, inplace=True)

    return df_sorted
df_sorted = sort_by_date(df_gb_cleaned, 'date')
display(df_sorted)

,ecoregion_name,country_name,distance_to_shore,exposure,cyclone_frequency,bleaching_level,percent_bleaching,climsst,ssta,ssta_standard_deviation,date
0,Central and northern Great Barrier Reef,Australia,2865.08,Sheltered,43.52,Population,6.50,296.78,1.64,1.02,2015-07-25
1,Central and northern Great Barrier Reef,Australia,2795.93,Sheltered,43.52,Population,8.75,296.78,1.64,1.02,2015-07-25
2,Central and northern Great Barrier Reef,Australia,216.38,Sometimes,43.39,Population,13.25,296.52,1.11,0.98,2015-07-26
3,Central and northern Great Barrier Reef,Australia,326.99,Sheltered,43.39,Population,24.25,296.53,1.11,0.96,2015-07-26
4,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,3.00,297.64,0.30,0.88,2015-08-02
5,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,2.00,297.64,0.30,0.88,2015-08-02
6,Central and northern Great Barrier Reef,Australia,38514.12,Sheltered,48.80,Population,13.75,298.86,1.43,0.84,2015-08-29
7,Central and northern Great Barrier Reef,Australia,38506.76,Sheltered,48.80,Population,22.50,298.86,1.43,0.84,2015-08-29
8,Central and northern Great Barrier Reef,Australia,35199.40,Sheltered,50.97,Population,28.75,298.87,0.83,0.88,2015-08-30
9,Central and northern Great Barrier Reef,Australia,37626.29,Sheltered,52.46,Population,3.25,298.90,0.95,0.87,2015-08-30
10,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,67.50,299.47,0.22,0.85,2015-09-12
11,Central and northern Great Barrier Reef,Australia,39847.16,Sheltered,71.88,Population,3.25,299.42,0.22,0.84,2015-09-13
12,Central and northern Great Barrier Reef,Australia,46945.93,Sheltered,60.01,Population,8.75,299.46,0.19,0.85,2015-09-13
13,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,4.50,298.91,-2.03,2.48,2015-10-01
14,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,12.50,299.85,-0.72,0.88,2015-10-02
15,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,35.00,299.85,-0.72,0.88,2015-10-02
16,Central and northern Great Barrier Reef,Australia,224.53,Exposed,43.52,Population,2.25,301.69,-0.09,1.02,2015-10-24
17,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,0.75,301.69,-0.14,0.98,2015-10-24
18,Southern Great Barrier Reef,Australia,2173.19,Sheltered,51.57,Population,1.00,299.92,0.42,0.73,2015-11-24
19,Southern Great Barrier Reef,Australia,1345.62,Sheltered,51.57,Population,1.00,299.92,0.42,0.73,2015-11-24
20,Southern Great Barrier Reef,Australia,54.69,Sheltered,51.46,Population,0.25,299.83,0.00,0.72,2015-11-24
21,Southern Great Barrier Reef,Australia,94.80,Sheltered,51.46,Population,1.00,299.99,0.39,0.72,2015-11-25
22,Southern Great Barrier Reef,Australia,1739.41,Exposed,51.57,Population,1.00,299.99,0.39,0.72,2015-11-25
23,Southern Great Barrier Reef,Australia,1152.07,Exposed,51.57,Population,1.00,299.99,0.39,0.72,2015-11-25
24,Southern Great Barrier Reef,Australia,226.58,Sheltered,51.46,Population,5.75,299.99,0.39,0.72,2015-11-26
25,Southern Great Barrier Reef,Australia,665.19,Sheltered,51.46,nd,95.50,299.99,0.39,0.72,2015-11-27
26,Southern Great Barrier Reef,Australia,459.75,Sheltered,51.46,Population,0.75,299.99,0.39,0.72,2015-11-27
27,Southern Great Barrier Reef,Australia,192.41,Sheltered,51.46,Population,4.25,299.99,0.39,0.72,2015-11-27
28,Southern Great Barrier Reef,Australia,782.39,Sheltered,51.57,Population,1.00,299.99,0.39,0.72,2015-11-28
29,Southern Great Barrier Reef,Australia,847.35,Exposed,51.57,Population,1.00,299.99,0.39,0.72,2015-11-28
30,Southern Great Barrier Reef,Australia,95.43,Sheltered,51.57,Population,1.00,299.99,0.39,0.72,2015-11-28
31,Southern Great Barrier Reef,Australia,106.65,Sheltered,51.57,Population,1.00,299.99,0.39,0.72,2015-11-29
32,Southern Great Barrier Reef,Australia,840.60,Sometimes,43.06,Population,8.75,297.78,1.32,0.87,2016-03-26
33,Southern Great Barrier Reef,Australia,26.88,Sheltered,43.06,Population,6.25,297.78,1.32,0.87,2016-03-26
34,Southern Great Barrier Reef,Australia,211.24,Sheltered,39.06,Population,25.00,298.21,1.07,0.81,2016-03-27
35,Southern Great Barrier Reef,Australia,247.29,Exposed,39.06,Population,11.25,298.17,0.87,0.82,2016-03-27
36,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,4.50,297.14,0.39,0.98,2016-04-09
37,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,8.25,297.14,0.39,0.98,2016-04-09
38,Central and northern Great Barrier Reef,Australia,224.53,Exposed,43.52,Population,4.75,297.02,0.34,1.02,2016-04-10
39,Central and northern Great Barrier Reef,Australia,46945.93,Sheltered,60.01,Population,60.00,298.34,0.92,0.85,2016-04-17
40,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,72.50,298.15,0.64,0.85,2016-04-17
41,Central and northern Great Barrier Reef,Australia,39227.48,Sheltered,71.88,Population,58.75,298.16,0.79,0.84,2016-04-17
42,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,Population,40.00,296.79,0.43,0.88,2016-04-23
43,Central and northern Great Barrier Reef,Australia,49.79,Sheltered,46.88,Population,9.25,298.77,0.56,2.42,2016-04-23
44,Central and northern Great Barrier Reef,Australia,562.43,Sheltered,47.44,nd,95.50,296.79,0.43,0.88,2016-04-24
45,Central and northern Great Barrier Reef,Australia,22.86,Sheltered,45.33,nd,95.50,296.21,0.25,0.93,2016-04-25
46,Central and northern Great Barrier Reef,Australia,46.06,Sheltered,45.33,nd,95.50,296.21,0.25,0.93,2016-04-25
47,Central and northern Great Barrier Reef,Australia,35199.40,Sheltered,50.97,Population,56.25,297.67,0.82,0.88,2016-04-30
48,Central and northern Great Barrier Reef,Australia,31869.41,Sometimes,52.46,Population,52.50,297.55,1.60,0.87,2016-04-30
49,Central and northern Great Barrier Reef,Australia,29008.14,Sheltered,48.10,Population,9.50,295.74,1.73,0.77,2016-05-28
50,Central and northern Great Barrier Reef,Australia,29934.17,Sheltered,48.10,Population,4.75,295.74,1.73,0.77,2016-05-28
51,Central and northern Great Barrier Reef,Australia,40871.05,Sheltered,48.37,Population,17.25,298.51,0.06,2.23,2016-05-29
52,Central and northern Great Barrier Reef,Australia,41586.65,Sheltered,48.37,Population,32.50,298.51,0.06,2.23,2016-05-29
53,Central and northern Great Barrier Reef,Australia,2795.93,Sheltered,43.52,Population,57.50,295.29,1.71,1.02,2016-06-25
54,Central and northern Great Barrier Reef,Australia,126.24,Sometimes,43.39,Population,5.00,295.18,1.64,0.98,2016-06-26
55,Central and northern Great Barrier Reef,Australia,350.30,Sheltered,43.39,Population,20.00,295.18,1.64,0.98,2016-06-26
56,Southern Great Barrier Reef,Australia,54.69,Sheltered,51.46,Population,2.75,297.05,0.38,0.72,2016-09-18
57,Southern Great Barrier Reef,Australia,2173.19,Sheltered,51.57,Population,6.50,297.07,0.53,0.73,2016-09-18
58,Southern Great Barrier Reef,Australia,1345.62,Sheltered,51.57,Population,4.25,297.07,0.53,0.73,2016-09-18
59,Southern Great Barrier Reef,Australia,1152.07,Exposed,51.57,Population,4.00,297.05,0.38,0.72,2016-09-19
60,Southern Great Barrier Reef,Australia,95.43,Sheltered,51.57,Population,5.00,297.05,0.38,0.72,2016-09-19
61,Southern Great Barrier Reef,Australia,1739.41,Exposed,51.57,Population,2.00,297.05,0.38,0.72,2016-09-19
62,Southern Great Barrier Reef,Australia,847.35,Exposed,51.57,Population,1.00,297.05,0.38,0.72,2016-09-20
63,Southern Great Barrier Reef,Australia,226.58,Sheltered,51.46,Population,10.00,297.05,0.38,0.72,2016-09-20
64,Southern Great Barrier Reef,Australia,665.19,Sheltered,51.46,Population,5.25,297.05,0.38,0.72,2016-09-20
65,Southern Great Barrier Reef,Australia,94.80,Sheltered,51.46,Population,15.25,297.05,0.38,0.72,2016-09-20
66,Southern Great Barrier Reef,Australia,106.65,Sheltered,51.57,Population,5.00,297.41,0.80,0.72,2016-09-21
67,Southern Great Barrier Reef,Australia,192.41,Sheltered,51.46,Population,5.00,297.41,0.80,0.72,2016-09-21
68,Southern Great Barrier Reef,Australia,184.65,Sheltered,51.57,Population,0.25,297.41,0.80,0.72,2016-09-22
69,Southern Great Barrier Reef,Australia,782.39,Sheltered,51.57,Population,0.75,297.41,0.80,0.72,2016-09-22
70,Southern Great Barrier Reef,Australia,459.75,Sheltered,51.46,Population,0.25,297.41,0.80,0.72,2016-09-22
71,Central and northern Great Barrier Reef,Australia,19577.87,Exposed,43.97,Population,17.50,299.09,0.70,2.58,2016-10-12
72,Central and northern Great Barrier Reef,Australia,33605.64,Sheltered,71.88,Population,4.00,301.42,0.24,0.86,2016-10-29
73,Central and northern Great Barrier Reef,Australia,53198.14,Exposed,50.40,Population,1.50,301.47,-0.20,0.87,2016-10-30
74,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,8.75,301.53,0.08,0.85,2016-10-30
75,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,10.00,301.53,0.08,0.85,2016-10-30
76,Central and northern Great Barrier Reef,Australia,2865.08,Sheltered,43.52,Population,1.00,298.70,1.94,1.02,2017-03-18
77,Central and northern Great Barrier Reef,Australia,2795.93,Sheltered,43.52,Population,1.00,298.70,1.94,1.02,2017-03-18
78,Central and northern Great Barrier Reef,Australia,216.38,Sometimes,43.39,Population,6.25,298.66,2.78,0.98,2017-03-19
79,Central and northern Great Barrier Reef,Australia,350.30,Sheltered,43.39,Population,6.00,298.66,2.78,0.98,2017-03-19
80,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,91.00,298.73,1.44,0.85,2017-04-01
81,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,95.50,298.73,1.44,0.85,2017-04-01
82,Central and northern Great Barrier Reef,Australia,39847.16,Sheltered,71.88,Population,75.75,298.73,0.85,0.84,2017-04-02
83,Central and northern Great Barrier Reef,Australia,46945.93,Sheltered,60.01,Population,77.50,298.90,1.25,0.85,2017-04-02
84,Central and northern Great Barrier Reef,Australia,34986.69,Sheltered,50.97,Population,42.75,297.67,-0.43,0.88,2017-04-30
85,Central and northern Great Barrier Reef,Australia,36098.44,Sheltered,50.97,Population,35.25,297.67,-0.43,0.88,2017-04-30
86,Central and northern Great Barrier Reef,Australia,35199.40,Sheltered,50.97,Population,31.00,297.67,-0.43,0.88,2017-04-30
87,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,65.00,296.86,-0.12,0.88,2017-05-01
88,Central and northern Great Barrier Reef,Australia,742.91,Sheltered,63.92,Population,35.00,296.86,-0.12,0.88,2017-05-01
89,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,2.25,294.89,-0.78,0.98,2017-06-09
90,Central and northern Great Barrier Reef,Australia,224.53,Exposed,43.52,Population,3.50,294.83,0.29,1.02,2017-06-09
91,Central and northern Great Barrier Reef,Australia,123.51,Sometimes,43.39,Population,2.00,294.89,-0.78,0.98,2017-06-09
92,Central and northern Great Barrier Reef,Australia,43199.05,Sheltered,43.31,Population,0.00,296.51,0.77,0.82,2017-07-07
93,Central and northern Great Barrier Reef,Australia,145.07,Exposed,43.52,Population,0.00,295.84,1.62,1.02,2017-07-07
94,Central and northern Great Barrier Reef,Australia,57425.12,Sheltered,48.94,Population,0.50,296.66,0.42,0.79,2017-07-08
95,Central and northern Great Barrier Reef,Australia,57761.46,Sheltered,48.94,Population,2.25,296.66,0.42,0.79,2017-07-08
96,Central and northern Great Barrier Reef,Australia,57656.01,Sheltered,48.94,Population,0.00,296.66,0.42,0.79,2017-07-09
97,Central and northern Great Barrier Reef,Australia,57467.04,Sheltered,48.94,Population,0.00,296.66,0.42,0.79,2017-07-09
98,Central and northern Great Barrier Reef,Australia,40871.05,Sheltered,48.37,Population,1.25,298.59,-2.30,2.23,2017-08-05
99,Central and northern Great Barrier Reef,Australia,41586.65,Sheltered,48.37,Population,0.00,298.59,-2.30,2.23,2017-08-05
100,Central and northern Great Barrier Reef,Australia,22.86,Sheltered,45.33,Population,33.75,296.48,1.76,0.93,2017-08-06
101,Central and northern Great Barrier Reef,Australia,19.02,Sheltered,45.33,Population,1.00,296.48,1.76,0.93,2017-08-06
102,Central and northern Great Barrier Reef,Australia,29487.39,Sheltered,48.10,Population,1.25,296.83,0.98,0.77,2017-08-07
103,Central and northern Great Barrier Reef,Australia,29008.14,Sheltered,48.10,Population,11.75,296.83,0.98,0.77,2017-08-07
104,Central and northern Great Barrier Reef,Australia,220.26,Exposed,43.52,Population,0.50,301.47,1.59,1.02,2017-10-15
105,Central and northern Great Barrier Reef,Australia,21755.41,Sheltered,36.00,Population,3.50,301.53,1.36,0.85,2017-10-28
106,Southern Great Barrier Reef,Australia,2173.19,Sheltered,51.57,Population,1.00,299.15,0.94,0.73,2017-10-29
107,Southern Great Barrier Reef,Australia,54.69,Sheltered,51.46,Population,6.50,299.08,0.82,0.72,2017-10-29
108,Central and northern Great Barrier Reef,Australia,20.86,Sheltered,44.24,Population,16.25,301.74,0.97,0.87,2017-10-29
109,Southern Great Barrier Reef,Australia,1345.62,Sheltered,51.57,Population,1.75,299.15,0.94,0.73,2017-10-29
110,Southern Great Barrier Reef,Australia,1739.41,Exposed,51.57,Population,4.25,299.08,0.82,0.72,2017-10-30
111,Southern Great Barrier Reef,Australia,1152.07,Exposed,51.57,Population,3.50,299.08,0.82,0.72,2017-10-30
112,Southern Great Barrier Reef,Australia,192.41,Sheltered,51.46,Population,15.00,299.08,0.82,0.72,2017-10-30
113,Southern Great Barrier Reef,Australia,847.35,Exposed,51.57,Population,1.00,299.08,0.82,0.72,2017-10-31
114,Southern Great Barrier Reef,Australia,95.43,Sheltered,51.57,Population,30.00,299.08,0.82,0.72,2017-10-31
115,Southern Great Barrier Reef,Australia,682.44,Exposed,51.46,Population,1.00,299.08,0.82,0.72,2017-10-31
116,Southern Great Barrier Reef,Australia,106.65,Sheltered,51.57,Population,25.00,299.35,0.82,0.72,2017-11-01
117,Southern Great Barrier Reef,Australia,226.58,Sheltered,51.46,Population,12.50,299.35,0.82,0.72,2017-11-01
118,Southern Great Barrier Reef,Australia,459.75,Sheltered,51.46,Population,1.25,299.35,0.82,0.72,2017-11-02
119,Southern Great Barrier Reef,Australia,782.39,Sheltered,51.57,Population,10.00,299.35,0.82,0.72,2017-11-02
120,Southern Great Barrier Reef,Australia,94.80,Sheltered,51.46,Population,17.50,299.35,0.82,0.72,2017-11-02
121,Southern Great Barrier Reef,Australia,930.80,Exposed,51.57,Population,2.00,299.35,0.82,0.72,2017-11-03
122,Southern Great Barrier Reef,Australia,665.19,Sheltered,51.46,Population,1.00,299.35,0.82,0.72,2017-11-03
123,Southern Great Barrier Reef,Australia,184.65,Sheltered,51.57,Population,10.00,299.35,0.82,0.72,2017-11-04

In [53]:
def plot_bleaching_over_time(df):
    # Ensure 'date' is in datetime format
    df['date'] = pd.to_datetime(df['date'])

    # Create a line plot
    fig = px.line(df, x='date', y='percent_bleaching', 
                  title='Percent Bleaching Over Time',
                  labels={'percent_bleaching': 'Percent Bleaching', 'date': 'Date'})

    # Customize the layout for better aesthetics
    fig.update_layout(xaxis_title='Date', yaxis_title='Percent Bleaching',
                      template='plotly_dark')  # Optional: Change to plotly or other templates

    # Show the plot
    fig.show()


plot_bleaching_over_time(df_gb_cleaned)